# Generated by Django 6.0.1 on 2026-01-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_predefined',
            field=models.BooleanField(default=False, help_text='Pre-defined category that cannot be deleted'),
        ),
    ]
