# Generated by Django 6.0.1 on 2026-05-02 00:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category_is_predefined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_capacity',
            field=models.IntegerField(default=1, help_text='Maximum number of clients for this service at one time', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='service_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('max_capacity__gte', 1)), name='service_max_capacity_min_1'),
        ),
    ]
