# Generated by Django 6.0.1 on 2026-06-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_category_color_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='svg_icon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
