# Generated by Django 6.0.1 on 2026-04-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_businessgalleryimage_image_type'),
        ('users', '0003_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
    ]
