# Generated by Django 6.0.1 on 2026-05-02 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in international format: '+998901234567'. 9-15 digits required.", regex='^\\+[1-9]\\d{8,14}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in international format: '+998901234567'.", regex='^\\+[1-9]\\d{8,14}$')]),
        ),
    ]
