# Generated by Django 6.0.1 on 2026-05-04 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Uzbek number: '+998901234567'.", regex='^\\+998\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Uzbek number: '+998901234567'.", regex='^\\+998\\d{9}$')]),
        ),
    ]
