# Generated by Django 6.0.1 on 2026-06-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_uzbek_phone_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
